sched-ext/sched_ext

- kernel/sched/ext.c
There's currently a race when invoking ops.set_weight() that could cause a warning to be emitted due to unexpected nesting. Most scx ops are always called either with or without interrupts being enabled. ops.set_weight() is a bit special in that it can be called both on the post-fork path from scx_post_fork(), or from switching_to_scx() / reweight_task_scx(), which are both called with the rq lock held and interrupts disabled. This can cause the following warning to be emitted if a timer interrupt is fired while executing the ops.set_weight() callback on the post-fork path:
[ 4975.435822] invalid nesting current->scx.kf_mask=0x20 mask=0x20 [ 4975.447670] WARNING: CPU: 33 PID: 431940 at kernel/sched/ext.c:213 select_task_rq_scx+0x173/0x190 ...
[ 4975.615777] RIP: …
> scx: Account for ops.set_weight() scx_post_fork() path

- tools/sched_ext/README
We've had some confusion on both the upstream list, and in issues open on the sched_ext GitHub repo, of folks who don't know whether an example sched_ext scheduler is or isn't expected to perform well. We have header comments in the .bpf.c files for these schedulers, but folks may not see them. Let's add a README file to the tools/sched_ext repo which enumerates the various example schedulers, and tells people how to compile them.
> scx: Further document example schedulers

- tools/sched_ext/atropos/Cargo.toml
Most distributions provide a shared lib version of libclang, so building atropos is not as easy as it should be. #6 is an example of this being confusing to other developers.
We have no particular dependency on libclang being static, so this can be configured more conventionally.
> atropos: Remove static libclang dependency

- tools/sched_ext/scx_example_userland.bpf.c
In commit d02c48fa1139 ("bpf: Make struct task_struct an RCU-safe type"), bpf_task_acquire() was updated to be KF_RET_NULL. Eishun pointed out that the userland example scheduler no longer loads, and it's because the usersched_task() helper function in scx_example_userland originally used bpf_get_current_task_btf() to avoid having to do a NULL check in the caller, but this no longer works due to bpf_task_acquire() being NULL-able. Let's just remove that weird logic that used bpf_get_current_task_btf(). When bpf_assert() lands, we can just use that to simplify instead.
Fixes issue #9
> scx: Fix scx_example_userland missing NULL check

- tools/sched_ext/atropos/src/bpf/atropos.bpf.c
- tools/sched_ext/scx_example_central.bpf.c
- tools/sched_ext/scx_example_flatcg.bpf.c
- tools/sched_ext/scx_example_pair.bpf.c
- tools/sched_ext/scx_example_qmap.bpf.c
- tools/sched_ext/scx_example_simple.bpf.c
- tools/sched_ext/scx_example_userland.bpf.c
When a BPF scheduler user-space program exits, the struct_ops map that it attaches to to load the BPF program is not automatically detached. This can cause the map and progs to remain loaded, which in turn will cause future attempts to load a new scheduling program to fail.
In commit 8d1608d70927 ("libbpf: Create a bpf_link in bpf_map__attach_struct_ops()"), Kui-feng updated
bpf_map__attach_struct_ops() to create an actual link for the struct_ops map, which in turn makes it automatically close the map when the owning program exits. This patch updates the example schedulers to leverage this by updating their sections to SEC(".struct_ops.link").
> scx: Auto-release example scheduler struct_ops on program exit

- kernel/sched/ext.c
- tools/sched_ext/atropos/src/bpf/atropos.bpf.c
- tools/sched_ext/scx_example_central.bpf.c
- tools/sched_ext/scx_example_flatcg.bpf.c
- tools/sched_ext/scx_example_pair.bpf.c
- tools/sched_ext/scx_example_qmap.bpf.c
- tools/sched_ext/scx_example_simple.bpf.c
- tools/sched_ext/scx_example_userland.bpf.c
When a BPF scheduler user-space program exits, the struct_ops map that                                                                                                                        
it attaches to to load the BPF program is not automatically detached.                                                                                                                         
This can cause the map and progs to remain loaded, which in turn will                                                                                                                         
cause future attempts to load a new scheduling program to fail.                                                                                                                               
In commit 8d1608d70927 ("libbpf: …
> Add proper support for auto-detach in sched_ext

- include/linux/sched/ext.h
- kernel/sched/core.c
- kernel/sched/ext.c
- kernel/sched/ext.h
- tools/sched_ext/atropos/Cargo.toml
- tools/sched_ext/atropos/src/bpf/atropos.bpf.c
- tools/sched_ext/atropos/src/bpf/atropos.h
- tools/sched_ext/atropos/src/main.rs
- tools/sched_ext/scx_common.bpf.h
- tools/sched_ext/scx_example_flatcg.bpf.c
- tools/sched_ext/scx_example_qmap.bpf.c
- tools/sched_ext/scx_example_simple.bpf.c
- tools/sched_ext/scx_example_userland.bpf.c
Fixes for a couple tricky bugs and an improvement to select_cpu_dfl().
*  All schedulers w/ vtime scheduling wasn't updating p->dsq.vtime on scheduler reloads or, if applicable, cgroup migrations. This could get some unlucky tasks stuck way in the future stalling them severely. It's likely that we haven't noticed this with web benchmarks because web machines never completely peg themselves.
* ttwu_queue path skips select_cpu() which can confuse some of the SCX schedulers. Fixed by disabling ttwu_queue for tasks on SCX.
* It turned out that going for a different CPU whose SMT siblings are all idle is usually better than sticking with partially free @prev_cpu. select_cpu_dfl() is updated accordingly.
Atropos saw a lot of updates:
* Execution stall bug caused by queueing on and waking …
> Bug fixes and a lot of atropos updates

- kernel/sched/ext.c
- kernel/sched/ext.h
- tools/sched_ext/atropos/src/bpf/atropos.bpf.c
While "core" is a heavily overloaded word, it's what used inside the kernel to describe a whole physical SMT group. Let's use that in SCX and atropos too.
> SCX: Use "idle core" instead of "whole cpu"

- tools/sched_ext/scx_atropos/Cargo.toml
- tools/sched_ext/scx_atropos/src/main.rs
Update libbpf-rs and libbpf-cargo to 0.21, which is the most recent version. Also update libbpf-sys to 1.2.0, which is a requirement for .struct_ops.link support that the program uses (and which got added with libbpf 1.2).
> scx_atropos: Update various dependencies

- kernel/sched/ext.h
task_on_scx() takes a struct task_struct *p, but it's called by __task_prio() in CONFIG_SCHED_CORE which takes a const struct task_struct *. This can cause the build to fail due to incompatible pointer types:
kernel/sched/core.c:170:18: error: passing 'const struct task_struct *' to parameter of type 'struct task_struct *' discards qualifiers [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
if (task_on_scx(p))
^
kernel/sched/ext.h:124:52: note: passing argument to parameter 'p' here static inline bool task_on_scx(struct task_struct *p)
Fix task_on_scx() so this doesn't happen.
> scx: Make task_on_scx() take const task_struct

- tools/sched_ext/scx_atropos/Cargo.toml
- tools/sched_ext/scx_atropos/src/main.rs
fb-procfs crate supports hotplug CPUs now, so migrate back to that for measuring CPU util.
> scx: atropos: Use fb-procfs crate

- tools/sched_ext/scx_central.c
- tools/sched_ext/scx_flatcg.c
- tools/sched_ext/scx_pair.c
- tools/sched_ext/scx_qmap.c
- tools/sched_ext/scx_simple.c
- tools/sched_ext/scx_userland.c
When trying to compile the schedulers from source in different contexts, it can be a pain to use the kernel types. Let's update the schedulers to use the types exported from UAPI headers, and get rid of the _GNU_SOURCE macro.
> scx: Convert user space schedulers to use __{s,u}{32,64} types

- tools/sched_ext/Makefile
- tools/sched_ext/scx_central.c
- tools/sched_ext/scx_flatcg.c
- tools/sched_ext/scx_pair.c
- tools/sched_ext/scx_qmap.c
- tools/sched_ext/scx_simple.c
- tools/sched_ext/scx_user_common.h
- tools/sched_ext/scx_userland.c
On some build systems, asserts are compiled out. We're currently using asserts on some actual operations, such as loading a prog. Let's update all of our progs to explicitly check return values where appropriate so we don't accidentally compile out real logic.
> scx: Use explicit checks instead of asserts

- tools/sched_ext/scx_rusty/src/bpf/rusty.bpf.c
rusty.bpf.c has a few small places where we can improve either the formatting of the code, or the logic. In rusty_select_cpu(), we declare the idle_smtmask as struct cpumask *, when it could be const. Also, when initializing the pcpu_ctx, we're using an actual for-loop instead of bpf_for. Let's just fix up these small issues.
> scx: Adjust a couple of small things in rusty.bpf.c

- tools/sched_ext/user_exit_info.h
When used from a bpf scheduler that is launched via libbpf-rs this naming runs into issues because "type" is a reserved keyword in Rust.
> scx: Rename "type" -> "exit_type"

- include/linux/sched/ext.h
The struct cpumask * argument to the ops.set_cpumask() op isn't const. It doesn't really matter in terms of mutability in a BPF program, but let's make it const just because it really is.
> scx: Make cpumask arg to ops.set_cpumask() const

- kernel/sched/ext.c
Some of the sched_ext kfuncs are fine to call from tracepoints. For example, we may want to call scx_bpf_error_bstr() if some error condition is detected in a tracepoint rather than a sched_ext ops callback. This patch therefore separates the scx_kfunc_ids_any kfunc BTF set into two sets: one of which includes kfuncs that can only be called from struct_ops, and the other which can be called from both struct_ops and tracepoint progs.
> scx: Allow calling some kfuncs from tracepoints

- include/linux/sched/ext.h
- kernel/sched/ext.c
- kernel/sched/sched.h
Some 32bit archs can't do 64bit store_release/load_acquire. Switch to atomic_long_t and unsigned longs.
> Use unsigned longs for atomics

- tools/sched_ext/scx_central.bpf.c
- tools/sched_ext/scx_central.c
- tools/sched_ext/scx_common.bpf.h
- tools/sched_ext/scx_pair.bpf.c
- tools/sched_ext/scx_pair.c
- tools/sched_ext/scx_pair.h
- tools/sched_ext/scx_user_common.h
there are some percpu arrays in the example schedulers that can make use of a recent libbpf feature that allows for resizing global data sections. for select arrays, they can be placed in custom named data sections and then resized to match the actual cpu count on a given host.
shown below is the BTF dump of the central and pair example scheduler programs that shows the array lengths have changed (nr_elements) to match the 12-cpu host they were tested on. note the linkage has also changed. this is a result of making the arrays non-static which was needed to access them through the skeleton for resizing in the userspace program.
central_dispatch before:
[742] ARRAY '(anon)' type_id=97 index_type_id=4 nr_elems=4096
[743] VAR 'cpu_gimme_task' type_id=742, linkage=static
[744] ARRAY '(anon)' …
> use resizing of datasec maps in examples

- kernel/sched/ext.c
The function is currently returning 0 for unknown accesses which means allowing writes to anything. Fix the default return value.
> scx: bpf_scx_btf_struct_access() should return -EACCES for unknown accesses

- include/linux/sched/ext.h
- kernel/sched/ext.c
p->scx.flag is protected by the task's rq lock but one of the flags, SCX_TASK_ON_DSQ_PRIQ, is protected by p->dsq->lock, not its rq lock. This could lead to corruption of p->scx.flags through RMW races triggering watchdog and other sanity checks. Fix it moving it to its own flag field p->scx.dsq_flags which is protected by the dsq lock.
> scx: Fix p->scx.flags corruption due to unsynchronized writes of SCX_TASK_ON_DSQ_PRIQ

- tools/sched_ext/scx_central.bpf.c
- tools/sched_ext/scx_central.c
Researchers at Inria-Paris are experimenting with the central scheduler, and want to try setting different slice lengths to see how they affect performance for VMs running the NAS benchmarks. Let's make this convenient by allowing it to be passed as a parameter from user space.
> central: Allow specifying the slice length in the central scheduler

- kernel/sched/ext.c
There's a comment that says can_stop_tick_scx(). The function is scx_can_stop_tick().
> scx: Fix typo in tickless comment

- tools/sched_ext/scx_central.bpf.c
- tools/sched_ext/scx_central.c
The scx_central scheduler specifies an infinite slice for all cores other than a "central" core where scheduling decisions are made. This scheduler currently suffers from the fact that the BPF timer may be invoked on a different core than the central scheduler, due to BPF timers not supporting being pinned to specific CPUs.
That capability was proposed upstream for BPF in [0]. If and when it lands, we would need to invoke bpf_timer_start() from the core that we want the timer pinned to, because the API does not support specifying a core to have the timer invoked from. To accommodate this, we can affinitize the loading thread to the central CPU before loading the scheduler, and then pin from there.
[0]: https://lore.kernel.org/bpf/20231002234708.331192-2-void@manifault.com/T/
Though the …
> central: Pin timer callbacks to central CPU

- tools/sched_ext/README
We were previously under the impression that the rustup nightly toolchain was required to build the schedulers. Daan pointed out in [0] that he was able to build with stable, and I similarly was able to build with rust stable 1.70.0. Let's update the README accordingly.
[0]: https://github.com/sched-ext/sched_ext/issues/57
We also update the README to not explicitly require compiling the schedulers with
$ make LLVM=1 CC=clang
The BPF schedulers are automatically compiled with clang. If you compile this way, the user space portions will be compiled with gcc, which is fine.
> scx: Don't specify nightly rustup as dependency

- tools/sched_ext/Makefile
As described in https://github.com/sched-ext/sched_ext/issues/56, our build system has some deficiencies. You can't direct build artifacts to specific paths using e.g. O=, or install the schedulers to global paths. The build system is also a bit messy, with a good amount of copy-pasted code that could be refactored.
Let's improve the situation a bit.  This addresses all the issues Daan pointed out in https://github.com/sched-ext/sched_ext/issues/56.
> Update and refactor scheduler build system

- tools/sched_ext/Makefile
We previously separated the scx_rusty build into two steps -- a step to download dependencies, and another to build. That mostly works, except that the download-dependencies step is always run before the build step as it's a dependency. Even though it doesn't download any cargo dependencies, it still accesses the network.
Let's add a way for builders to pass --offline to cargo via a CARGO_OFFLINE make variable.
> rusty: Further tweak build system

- kernel/sched/ext.c
Fix breakage introduced by upstream change to how PF_IDLE is set. This fixes #69.
> Fix sched_ext crashes on v6.6

- kernel/sched/core.c
cpu_local_stat_show() expects CONFIG_SCHED_CLASS_EXT or CONFIG_RT_GROUP_SCHED.
> scx: Fix !CONFIG_SCHED_CLASS_EXT builds

- include/linux/sched/ext.h
- kernel/sched/core.c
- kernel/sched/ext.c
- lib/dump_stack.c
It would be useful to see what the sched_ext scheduler state is, and what scheduler is running, at panic time. Let's add a hook and print that information.
> scx: Print scheduler state in panic message

- kernel/sched/ext.c
The new print_scx_info() uses scx_ops_enable_state_str[] outside CONFIG_SCHED_DEBUG. Let's relocated it outside of CONFIG_SCHED_DEBUG and to the top.
Reported-by: Changwoo Min <changwoo@igalia.com>
Reported-by: Andrea Righi <andrea.righi@canonical.com>
> scx: Move scx_ops_enable_state_str[] outside CONFIG_SCHED_DEBUG

- fs/kernfs/dir.c
- kernel/sched/ext.c
There is a race with exiting tasks in scx_move_tasks() where we may fail to check for autogroup tasks, leading to the following oops:
WARNING: CPU: 2 PID: 100 at kernel/sched/ext.c:2571 scx_move_task+0x9f/0xb0
...
Sched_ext: flatcg (enabled+all), task: runnable_at=-5ms
RIP: 0010:scx_move_task+0x9f/0xb0
Call Trace:
<TASK>
? scx_move_task+0x9f/0xb0
? __warn+0x85/0x170
? scx_move_task+0x9f/0xb0
? report_bug+0x171/0x1a0
? handle_bug+0x3b/0x70
? exc_invalid_op+0x17/0x70
? asm_exc_invalid_op+0x1a/0x20
? scx_move_task+0x9f/0xb0
sched_move_task+0x104/0x300
do_exit+0x37d/0xb70
? lock_release+0xbe/0x270
do_group_exit+0x37/0xa0
__x64_sys_exit_group+0x18/0x20
do_syscall_64+0x44/0xf0
entry_SYSCALL_64_after_hwframe+0x6f/0x77
And a related NULL pointer dereference afterwards:
BUG: kernel NULL pointer …
> sched_ext: fix race in scx_move_task() with exiting tasks

- Documentation/scheduler/sched-ext.rst
- include/linux/sched/ext.h
- init/init_task.c
- kernel/sched/core.c
- kernel/sched/ext.c
- kernel/sched/ext.h
- tools/testing/selftests/scx/.gitignore
- tools/testing/selftests/scx/Makefile
- tools/testing/selftests/scx/enq_last_no_enq_fails.bpf.c
- tools/testing/selftests/scx/enq_last_no_enq_fails.c
- tools/testing/selftests/scx/enqueue_select_cpu_fails.bpf.c
- tools/testing/selftests/scx/enqueue_select_cpu_fails.c
- tools/testing/selftests/scx/scx_test.h
- tools/testing/selftests/scx/select_cpu_dfl.bpf.c
- tools/testing/selftests/scx/select_cpu_dfl.c
- tools/testing/selftests/scx/select_cpu_dfl_nodispatch.bpf.c
- tools/testing/selftests/scx/select_cpu_dfl_nodispatch.c
- tools/testing/selftests/scx/select_cpu_dispatch.bpf.c
- tools/testing/selftests/scx/select_cpu_dispatch.c
- tools/testing/selftests/scx/select_cpu_dispatch_bad_dsq.bpf.c
- tools/testing/selftests/scx/select_cpu_dispatch_bad_dsq.c
- tools/testing/selftests/scx/select_cpu_dispatch_dbl_dsp.bpf.c
- tools/testing/selftests/scx/select_cpu_dispatch_dbl_dsp.c
A common pattern in schedulers is to find and reserve an idle core in
`ops.select_cpu()`, and to then use a task local storage map to specify
that the task should be enqueued in `SCX_DSQ_LOCAL` on the `ops.enqueue()`
path. At the same time, we also have a special `SCX_TASK_ENQ_LOCAL`
enqueue flag which is used by `scx_select_cpu_dfl()` to notify
`ops.enqueue()` that it may want to do a local enqueue.
Taking a step back, direct dispatch is something that should be
supported from the `ops.select_cpu()` path as well. At the end of the day,
it's on the same "enqueue path" as `ops.enqueue()`, and if we have the
contract be that doing a direct dispatch to `SCX_DSQ_LOCAL` will dispatch
the task to the local CPU of whatever is returned by `ops.select_cpu()`, it
should improve the ergonomics of …
> Allow dispatching from ops.select_cpu()

- kernel/sched/ext.c
- tools/testing/selftests/scx/.gitignore
- tools/testing/selftests/scx/Makefile
- tools/testing/selftests/scx/dsp_fallbackdsq_fail.bpf.c
- tools/testing/selftests/scx/dsp_fallbackdsq_fail.c
We're currently checking whether a builtin DSQ is being used with priq
in scx_bpf_dispatch_vtime(). This neglects the fact that we could end up
falling back to scx_dsq_global if there's an error. If we error out with
SCX_ENQ_DSQ_PRIQ set in enqueue flags, we would trigger a warning in
dispatch_enqueue(). Let's instead just move the check to inside of
dispatch_enqueue().
> Fix fallback

- include/linux/sched/ext.h
- init/init_task.c
- kernel/sched/ext.c
- tools/testing/selftests/scx/.gitignore
- tools/testing/selftests/scx/Makefile
- tools/testing/selftests/scx/dsp_localdsq_fail.bpf.c
- tools/testing/selftests/scx/dsp_localdsq_fail.c
- tools/testing/selftests/scx/init_enable_count.bpf.c
- tools/testing/selftests/scx/init_enable_count.c
- tools/testing/selftests/scx/select_cpu_dfl_nodispatch.bpf.c
- A task's scx.weight is properly set before ops.enable() on the fork path, but not on the BPF prog load path. Set it properly for both.
- ops.enable() (and a corresponding ops.disable()) is called once for every task on the system on the BPF prog load path, or the fork path. It would be useful to instead call ops.enable() whenever a task is about to run on scx, and ops.disable() whenever a task is no longer running on scx.
> Fix and update semantics for ops.enable() and ops.disable()

- kernel/sched/ext.c
- tools/testing/selftests/scx/select_cpu_dfl.bpf.c
In scx_select_cpu_dfl(), we're currently returning prev_cpu if
p->nr_cpus_allowed == 1. It makes sense to return prev_cpu if the task
can't run on any other cores, but we might as well also try to claim the
core as idle so that:
1. scx_select_cpu_dfl() will directly dispatch it
2. To prevent another core from incorrectly assuming that core will be
idle when in reality that task will be enqueued to it. The mask will
eventually be updated in __scx_update_idle(), but this seems more
efficient.
3. To have the idle cpumask bit be unset when the task is enqueued in
ops.enqueue() (if the core scheduler is using
scx_bpf_select_cpu_dfl()).
> Claim idle core in scx_select_cpu_dfl for nr_cpus_allowed ==1

- kernel/sched/ext.c
If ops.select_cpu() isn't defined, scx_select_cpu_dfl() will be called, and a task will be dispatched directly to a core if one is found. I neglected to also set the task slice, so we see the following warning if we use the direct dispatch:
[root@arch scx]# ./select_cpu_dfl
[   23.184426] sched_ext: select_cpu_dfl[356] has zero slice in pick_next_task_scx()
I'm not sure why this wasn't being printed when I tested this before, but let's fix it.
> scx: Set default slice for default select_cpu dispatch

- kernel/sched/ext.c
Han Xing Yi reported a syzbot lockdep error over the weekend:
====================================================== WARNING: possible circular locking dependency detected 6.6.0-g2f6ba98e2d3d #4 Not tainted
------------------------------------------------------ syz-executor.0/2181 is trying to acquire lock:
ffffffff84772410 (pernet_ops_rwsem){++++}-{3:3}, at: copy_net_ns+0x216/0x590 net/core/net_namespace.c:487 but task is already holding lock:
ffffffff8449dc50 (scx_fork_rwsem){++++}-{0:0}, at: sched_fork+0x3b/0x190 kernel/sched/core.c:4810 which lock already depends on the new lock.
the existing dependency chain (in reverse order) is: -> #3 (scx_fork_rwsem){++++}-{0:0}:
percpu_down_write+0x51/0x210 kernel/locking/percpu-rwsem.c:227
scx_ops_enable+0x230/0xf90 kernel/sched/ext.c:3271 …
> scx: Avoid possible deadlock with cpus_read_lock()

- include/linux/sched/ext.h
- init/init_task.c
- kernel/sched/build_policy.c
- kernel/sched/core.c
- kernel/sched/ext.c
- kernel/sched/ext.h
- kernel/sched/sched.h
#102 reports that `scx_userland` and `scx_rustland` trigger stall failure on system suspend attempts. The problem is that these schedulers need userspace running for scheduling to work. Because during suspend and other PM operations, all user and some kernel threads are frozen during preparation, scheduling stops working triggering either freezer timeout or scx watchdog.
In #102, @arighi worked around by preemptively ejecting the sched_ext scheduler. While it's possible to implement userspace hooks to reload the scheduler after PM operations are finished, it's rather inconvenient and unnecessary. In terms of scheduling, there isn't anything interesting happening while the PM operations are in progress, so all we need to do is not stalling the system.
In the ops disabling path, we're …
> Implement generic bypass mode and use it while PM operations are in progress

- kernel/sched/ext.c
This reverts commit c3c7041b04c7fe1e80f7a558fed494f82f204618.
We hit a locking ordering issue in the other direction. Let's revert for now.
[    9.378773] ======================================================
[    9.379476] WARNING: possible circular locking dependency detected
[    9.379532] 6.6.0-work-10442-ga7150a9168f8-dirty #134 Not tainted
[    9.379532] ------------------------------------------------------
[    9.379532] scx_rustland/1622 is trying to acquire lock:
[    9.379532] ffffffff8325f828 (cpu_hotplug_lock){++++}-{0:0}, at: bpf_scx_reg+0xe4/0xcf0
[    9.379532]
[    9.379532] but task is already holding lock:
[    9.379532] ffffffff83271be8 (scx_cgroup_rwsem){++++}-{0:0}, at: bpf_scx_reg+0xdf/0xcf0
[    9.379532]
[    9.379532] which lock already depends on the new lock. …
> Revert "scx: Avoid possible deadlock with cpus_read_lock()"

- include/linux/sched/ext.h
- init/init_task.c
- kernel/sched/core.c
- kernel/sched/ext.c
- tools/testing/selftests/scx/.gitignore
- tools/testing/selftests/scx/Makefile
- tools/testing/selftests/scx/select_cpu_vtime.bpf.c
- tools/testing/selftests/scx/select_cpu_vtime.c
We're currently not remembering enq flags during direct dispatch. Let's
record them in case someone wants to pass e.g. SCX_ENQ_PREEMPT from
ops.select_cpu().
Let's also reset ddsq_id and ddsq_enq_flags before calling
dispatch_enqueue() to ensure there's no races with the task being
consumed from another core.
> Stash enq_flags when marking for direct dispatch

- tools/testing/selftests/scx/Makefile
- tools/testing/selftests/scx/ddsp_bogus_dsq_fail.bpf.c
- tools/testing/selftests/scx/ddsp_bogus_dsq_fail.c
- tools/testing/selftests/scx/ddsp_vtimelocal_fail.bpf.c
- tools/testing/selftests/scx/ddsp_vtimelocal_fail.c
- tools/testing/selftests/scx/scx_test.h
- tools/testing/selftests/scx/select_cpu_dfl.c
- tools/testing/selftests/scx/select_cpu_dfl_nodispatch.c
- tools/testing/selftests/scx/select_cpu_dispatch.c
- tools/testing/selftests/scx/select_cpu_dispatch_bad_dsq.c
- tools/testing/selftests/scx/select_cpu_dispatch_dbl_dsp.c
- tools/testing/selftests/scx/select_cpu_vtime.c
Now that the framework has been merged, let's update the remaining
testcases to use it. Do a bit of cleanup as well to deduplicate exit-error
validation logic.
> scx: Convert remaining testcases to use new framework

- include/linux/sched/ext.h
- kernel/sched/ext.c
Fix the locking order issue reported by Han Xing Yi <hxingyi104@gmail.com>. The first attempt #108 tripped lockdep in the other direction. Hopefully, this one should work out.
```
====================================================== WARNING: possible circular locking dependency detected 6.6.0-g2f6ba98e2d3d https://github.com/sched-ext/sched_ext/pull/4 Not tainted
------------------------------------------------------ syz-executor.0/2181 is trying to acquire lock:
ffffffff84772410 (pernet_ops_rwsem){++++}-{3:3}, at: copy_net_ns+0x216/0x590 net/core/net_namespace.c:487 but task is already holding lock:
ffffffff8449dc50 (scx_fork_rwsem){++++}-{0:0}, at: sched_fork+0x3b/0x190 kernel/sched/core.c:4810 which lock already depends on the new lock.
the existing dependency chain (in reverse …
```
> scx: Fix locking order

- .github/workflows/run-schedulers
- .github/workflows/sched-ext.config
- .github/workflows/test-kernel.yml
- .gitignore
Add a github action to test the sched-ext kernel with all the shipped schedulers.
The test uses a similar approach to the scx workflow [1], using virtme-ng to run each scheduler inside a sched-ext enabled kernel for a certain amount of time (30 sec) and checking for potential stall, oops or bug conditions.
In this case we can use `virtme-ng --build` to build a kernel with bare minimum support to run inside virtme-ng itself, instead of generating a fully featured kernel, to expedite the testing process.
The mandatory .config options required by sched-ext are stored in `.github/workflows/sched-ext.config` and they are passed to virtme-ng via the `--config` option.
The test itself is defined in `.github/workflows/run-schedulers`: the script looks for all the binaries in …
> ci: add github workflow to test the sched-ext kernel

- Documentation/scheduler/sched-ext.rst
- kernel/sched/build_policy.c
- kernel/sched/debug.c
- kernel/sched/ext.c
- kernel/sched/ext.h
- tools/sched_ext/scx_show_state.py
The existing state interface in /sys/kernel/debug/sched/ext is not available if CONFIG_SCHED_DEBUG is not set. Replace it with a simpler /sys/kernel/sched_ext interface and add tools/sched_ext/scx_show_state.py to keep the same level of visibility.
This will need updates in documentation and scripts in the scx repo.
> scx: Replace /sys/kernel/debug/sched/ext with /sys/kernel/sched_ext

- kernel/sched/ext.c
- tools/testing/selftests/scx/Makefile
- tools/testing/selftests/scx/maybe_null.bpf.c
- tools/testing/selftests/scx/maybe_null.c
- tools/testing/selftests/scx/maybe_null_fail.bpf.c
- tools/testing/selftests/scx/runner.c
This patch marks the second argument of .dispatch with
PTR_MAYBE_NULL | PTR_TO_BTF_ID | PTR_TRUSTED in
bpf_scx_is_valid_access(). The verifier  will ensures the programs
always check if the argument is NULL before reading the pointed memory.
> Make the pionter passing to .dispatch MAYBE_NULL

- kernel/sched/ext.c
- tools/testing/selftests/scx/Makefile
- tools/testing/selftests/scx/maybe_null.bpf.c
- tools/testing/selftests/scx/maybe_null.c
- tools/testing/selftests/scx/maybe_null_fail.bpf.c
- Fix a few typos and some comment formatting in ext.c
- Generalize the rule for compiling a "fail" testcase variant in seltests
- Update copyrights to 2024
> scx: Fix a couple follow ups to recent struct_ops changes

- include/linux/sched/ext.h
- kernel/sched/build_policy.c
- kernel/sched/ext.c
When a scx scheduler aborts, it can be difficult to find out what happened because all the scheduling states are lost as the system is reverted back to the default scheduler. Capture and dump the releavant states to aid debugging. In the future, it'd be useful to add `ops.dump()` and `ops.dump_task()` so that BPF scheduler can dump states specific to the BPF scheduler.
```
root@test ~# os/work/tools/sched_ext/build/bin/scx_qmap -t 500
enq=5, dsp=0, delta=5, reenq=0, deq=0, core=0
enq=451, dsp=445, delta=6, reenq=0, deq=0, core=0
enq=871, dsp=868, delta=3, reenq=0, deq=0, core=0
enq=1263, dsp=1259, delta=4, reenq=8, deq=0, core=0
enq=1595, dsp=1593, delta=2, reenq=8, deq=0, core=0
enq=1870, dsp=1869, delta=1, reenq=8, deq=0, core=0
enq=1940, dsp=1939, delta=1, reenq=8, deq=0, core=0 …
```
> Implement debug dump on abort

- kernel/sched/ext.c
> scx: rq should be locked when calling scx_ops_exit_task() from scx_cancel_fork()

- fs/kernfs/dir.c
- fs/kernfs/kernfs-internal.h
- include/linux/kernfs.h
Backport https://lore.kernel.org/all/20240109214828.252092-1-tj@kernel.org to fix kernfs locking issue which is triggered by `scx_flatcg` through `bpf_cgroup_from_id()`. Thanks to @sirlucjan for noticing the missing backport.
> kernfs: Backport kernfs locking fix patchset

- kernel/sched/ext.c
Trying to load multiple schedulers at the same time can trigger the following NULL pointer dereference:
[22053.942960] BUG: kernel NULL pointer dereference, address: 0000000000000000 [22053.942966] #PF: supervisor write access in kernel mode [22053.942968] #PF: error_code(0x0002) - not-present page [22053.942969] PGD 0 P4D 0
[22053.942972] Oops: 0002 [#1] PREEMPT SMP NOPTI
[22053.942976] CPU: 6 PID: 3550 Comm: sched_ext_ops_h Tainted: G           O       6.7.0-4-generic #4+scx3-Ubuntu
[22053.942978] Hardware name: GPD G1621-02/G1621-02, BIOS 2.04 09/01/2022
[22053.942980] Sched_ext: central (enabled+all)
[22053.942981] RIP: 0010:scx_ops_disable_workfn+0x85/0x610
[22053.942987] Code: 89 df f3 48 ab b9 01 00 00 00 83 fa 01 0f 86 c3 00 00 00 89 d0 f0 0f b1 0d 60 ff 11 02 0f 85 10 05 00 00 48 …
> scx: fix NULL pointer dereference with scx_exit_info

- include/linux/sched/ext.h
- kernel/sched/ext.c
- tools/testing/selftests/scx/init_enable_count.bpf.c
- tools/testing/selftests/scx/init_enable_count.c
- tools/testing/selftests/scx/runner.c
Some schedulers, such as scx_nest, want to have different logic
depending on whether a task was running prior to the scheduler being
enabled. Let's add a flag that they can check to make it easy to find
out.
We also add a testcase and add a slight usability improvement to the
test runner.
> Add fork field to struct scx_init_task_args

- kernel/sched/ext.c
And rearragent stuff a bit for better density.
> scx: Print p->cpus_ptr when dumping scheduler state

- kernel/sched/ext.c
This can be used to implement interlocking against dequeue. e.g, Let's say there is one dsq per CPU and the scheduler can stall if a task is dispatched to a dsq which doesn't intersect with p->cpus_ptr. In the dispatch path, if you do the following:
if (bpf_cpumask_test_cpu(target_cpu, p->cpus_ptr))
scx_bpf_dispatch(p, target_dsq, slice, 0);
The task can still end up in the wrong dsq because the cpumask can change between bpf_cpumask_test_cpu() and scx_bpf_dispatch(). However,
scx_bpf_dispatch(p, target_dsq, slice, 0);
if (!bpf_cpumask_test_cpu(target_cpu, p->cpus_ptr))
scx_bpf_dispatch_cancel();
eliminates the race window - either the set_cpumask path sees the task dispatched or the dispatch path sees the updated cpumask. In both cases, the dispatch gets canceled as it should.
Note that …
> scx: Implement scx_bpf_dispatch_cancel()

- .github/workflows/test-kernel.yml
We're basically always runnin two CI jobs: one for a remote push, and another for when a PR is opened. These are essentially measuring the same thing, so let's save CI bandwidth and just do a PR run. This will hopefully make things a bit less noisy as well.
> scx: Only do CI runs for PRs

- kernel/sched/ext.c
BPF kfuncs are a bit special in that they have global linkage, even if they're not called by any other function or compilation unit in the rest of the kernel. This has caused issues in some other parts of the codebase, and causes us to fail to compile starting in 6.8rc1. Let's apply the existing BPF macros to our kfuncs to avoid these issues.
> scx: Use BPF macros for sched_ext kfuncs

- kernel/sched/ext.c
- kernel/sched/ext.h
- kernel/sched/sched.h
Implement SCX_KICK_IDLE so that schedulers don't have to worry about causing too much churn with attempts to wake idle CPUs.
> scx: Implement SCX_KICK_IDLE

- kernel/sched/ext.c
To avoid crashing the kernel when CONFIG_CPUMASK_OFFSTACK is set.
> scx: Actually allocate rq->scx.cpus_to_kick_if_idle

- kernel/sched/ext.c
We're making two mistakes with respect to object lifecycle for scx_root_kobj:
- We're not calling kobject_put() if kobject_init_and_add() returns an
error code. According to the API for that function, we should be.
- We weren't kobject_putt()'ing scx_root_kobj on the
scx_ops_disable_workfn() path. We were calling kobject_del(), but this
doesn't actually call the release callback under the hood. It just
unlinks the kobject from the hierarchy.
Address both of these. With these changes, we no longer trigger the memory leak detected by Syzkaller in
https://github.com/sched-ext/sched_ext/issues/142. Without this patch, we see the following with memleak enabled:
unreferenced object 0xffff8dd78a99f000 (size 64):
comm "runner", pid 2383, jiffies 4294697813 (age 128.878s)
hex dump (first 32 …
> scx: Avoid memory leak of scx_root_kobj

- kernel/sched/ext.c
If scx_bpf_error() is triggered while a BPF scheduler is being loaded, depending on the point of failure, it can make ops_state transition fail and thus make loading fail with -EBUSY, which isn't very descriptive.
There was already a workaround for a specific case where ops.init() triggers scx_bpf_error() which works by just reporting success so that the usual exit path report the error with all the details.
There's no reason to restrict this to ops.init() failure. These early scx_bpf_error()s always make the ops_state transitions fail and we can always finish loading with success and let the exit path report the faliure.
> scx: Improve error reporting after an early scx_bpf_error()

- kernel/sched/ext.c
- kernel/sched/ext.h
sched_exec() calls select_task_rq() and then do a rq migration if the returned cpu is different from current. This calls ops.select_cpu() outside the normal enqueue path confusing the direct dispatch mechanism - e.g. rq->scx.ddsp_dsq_id can be asserted when it shouldn't be.
I tried to make ops.select_cpu() work in this path but the mechanism doesn't make whole lot of sense for scx and it makes the semantics around ops.select_cpu() unnecessarily complicated for rare corner cases. If we want this behavior, I think the right thing to do is adding a separate method which can preempt self to trigger the normal scheduling path for the task.
> scx: Ignore WF_EXEC

- kernel/sched/ext.c
scx_pm_handler() skips calling scx_ops_bypass() if !scx_enabled(). This means that if a SCX scheduler is loaded while PM operation is in progress, we can get an unbalanced scx_ops_bypass(%false) and vice-versa, which is easy to trigger using /dev/snapshot. Let's fix it by:
- Make scx_pm_handler() always call scx_ops_bypass().
- Synchronize scx_ops_bypass() against enable/disable path using scx_ops_enable_mutex and skip only the task update part when !scx_enabled().
Reported by @xingyiz in #153.
> scx: Fix scx_ops_bypass_depth going out of sync

- .github/workflows/test-kernel.yml
I changed my GitHub user name, so let's update the link to unblock CI.
> scx: Update .github workflow link

- include/linux/sched/ext.h
- kernel/sched/ext.c
- tools/sched_ext/include/scx/common.h
- tools/sched_ext/include/scx/compat.bpf.h
- tools/sched_ext/include/scx/compat.h
- tools/sched_ext/include/scx/user_exit_info.h
- tools/sched_ext/scx_central.bpf.c
- tools/sched_ext/scx_central.c
- tools/sched_ext/scx_flatcg.bpf.c
- tools/sched_ext/scx_flatcg.c
- tools/sched_ext/scx_qmap.bpf.c
- tools/sched_ext/scx_qmap.c
- tools/sched_ext/scx_simple.bpf.c
- tools/sched_ext/scx_simple.c
Schedulers can now request custom debug dump buffer size by setting `sched_ext_ops.exit_dump_len`. This will help debugging on bigger and busier systems.
> scx: Make exit debug dump buffer resizable

- kernel/sched/ext.c
reset_idle_masks() is called while loading a BPF scheduler to mark all CPUs as idle for scx_bpf_select_cpu_dfl(). It was cpumask_setall() which could make scx_bpf_select_cpu_dfl() pick a CPU which is possible but not online.
Note that such spurious picking can only happen one time and it's generally safe to pick an ineligible CPU, so nothing should be broken but the behavior isn't ideal. In general the initial values of idle masks aren't that important. They quickly get synchronized to the actual state through the CPUs entering and leaving the idle state.
However, let's still use cpu_online_mask instead so that the idle masks are initialized with online CPUs.
> scx: Use cpu_online_mask when resetting idle masks

- tools/testing/selftests/sched_ext/ddsp_bogus_dsq_fail.bpf.c
- tools/testing/selftests/sched_ext/ddsp_bogus_dsq_fail.c
- tools/testing/selftests/sched_ext/ddsp_vtimelocal_fail.bpf.c
- tools/testing/selftests/sched_ext/ddsp_vtimelocal_fail.c
- tools/testing/selftests/sched_ext/scx_test.h
- tools/testing/selftests/sched_ext/select_cpu_dispatch_bad_dsq.bpf.c
- tools/testing/selftests/sched_ext/select_cpu_dispatch_bad_dsq.c
- tools/testing/selftests/sched_ext/select_cpu_dispatch_dbl_dsp.bpf.c
- tools/testing/selftests/sched_ext/select_cpu_dispatch_dbl_dsp.c
The UEI macros were updated in a prior commit. Apply the changes to the sched_ext selftests dir.
Some of the tests are now broken as well. We should investigate.
> scx: Update selftests to use new UEI macros

- kernel/sched/ext.c
We want each successful `ops.cgroup_prep_move()` invocation to be always paired with an invocation of either `ops.cgroup_move()` or `ops.cgroup_cancel_move()`. However, this doesn't always hold because `sched_move_task()` implicitly ignores identity migrations skipping `ops.cgroup_move()` invocations. This lead to #164. Let's fix it by making `scx_cgroup_can_attach()` skip `ops.cgroup_prep_move()` calls on identity migrations.
> scx: cgroup: Fix mismatch between `ops.cgroup_prep_move()` and `ops.cgroup_move()` invocations

- kernel/sched/ext.c
In scx_select_cpu_dfl(), we currently migrate the waking task to the CPU of the waker in the following scenario:
1. WAKE_SYNC is specified in wake_flags
2. There is at least one idle core in the system
3. The wakee can run on the waker CPU
The assumption implicit with (2) is that the system is under saturated, and that therefore the wakee's runqueue delay would not be impacted by migrating to the waker's CPU rather than migrating to an idle core. This doesn't always happen in practice though. Consider the following scenario:
1. The system is overloaded, and at least one core becomes idle
2. Some groups of pairs of tasks that communicate over IPC are spawned.
3. Sender tasks are running on cores that still have enqueued tasks from when the system was overloaded, and they repeatedly wake …
> scx: Update conditions for WAKE_SYNC migration

- include/linux/sched/ext.h
- kernel/sched/ext.c
- kernel/sched/ext.h
- tools/sched_ext/include/scx/common.bpf.h
- tools/sched_ext/include/scx/user_exit_info.h
- tools/testing/selftests/sched_ext/Makefile
- tools/testing/selftests/sched_ext/exit.bpf.c
- tools/testing/selftests/sched_ext/exit.c
- tools/testing/selftests/sched_ext/exit_test.h
- tools/testing/selftests/sched_ext/init_enable_count.bpf.c
- tools/testing/selftests/sched_ext/init_enable_count.c
- tools/testing/selftests/sched_ext/scx_test.h
There may be cases where a scheduler wants to cause itself to exit under
normal circumstances. For example, if a scheduler does not support
hotplug, it may want to exit to user space if a CPU is hotplugged or
unplugged to let it know that it should restart itself.
To enable this, we implement a new kfunc called scx_bpf_exit_bstr().
This kfunc shares a good amount of logic with scx_bpf_error_bstr(), as
both of them can plumb an exit message from BPF to user space. In
addition, we also augment struct scx_exit_info to include an exit code
field.
> Allow clean exits from the scheduler with scx_bpf_exit()

- tools/sched_ext/include/scx/common.bpf.h
- tools/sched_ext/scx_flatcg.bpf.c
The flatcg scheduler uses a rb_node type - struct cgv_node - to keep track of vtime. On cgroup init, a cgv_node is created and stashed in a hashmap - cgv_node_stash - for later use. In cgroup_enqueued and try_pick_next_cgroup, the node is inserted into the rbtree, which required removing it from the stash before this patch's changes.
This patch makes cgv_node refcounted, which allows keeping it in the stash for the entirety of the cgroup's lifetime. Unnecessary bpf_kptr_xchg's and other boilerplate can be removed as a result.
Note that in addition to bpf_refcount patches, which have been upstream for quite some time, this change depends on a more recent series [0].
[0]: https://lore.kernel.org/bpf/20231107085639.3016113-1-davemarchevsky@fb.com/
> scx_flatcg: Keep cgroup rb nodes stashed

- tools/sched_ext/include/scx/compat.bpf.h
- tools/sched_ext/include/scx/compat.h
Where 0 fields are ignored if not present.
> scx: Use the new struct_ops compatibililty mechanism

- kernel/sched/ext.c
- tools/testing/selftests/sched_ext/Makefile
- tools/testing/selftests/sched_ext/prog_run.bpf.c
- tools/testing/selftests/sched_ext/prog_run.c
We'll want to be able to issue BPF_PROG_RUN calls in order to
synchronously call into the kernel from user space scheduling
components. The most natural prog type for this seems to be
BPF_PROG_TYPE_SYSCALL, which is a very safe program type. Let's allow
invoking the core kfuncs from this program type as well.
Signed-off-by: David Vernet <void@manifault.com>
> scx: Allow calling scx kfuncs from BPF_PROG_TYPE_SYSCALL

- kernel/sched/ext.c
- Make __bpf_kfunc_start/end_defs() blocks strict so that they only contain kfunc definitions.
- Match BTF_KFUNCS table with kfunc definition blocks so that they always come right after in the same order.
- Add function comment to scx_bpf_select_cpu_dfl() and rename @found to @is_idle which is more accurate and consistent with the BPF side declaration.
> scx: Cosmetic changes to kfuncs

- kernel/sched/ext.c
Had an extra "is", remove to make the sentence correct.
> scx: Fix trivial grammatical typo

- kernel/sched/ext.c
- tools/testing/selftests/sched_ext/prog_run.c
> scx: Spaces -> tabs in a couple places

- include/linux/sched/ext.h
- kernel/sched/ext.c
- kernel/sched/ext.h
- tools/sched_ext/include/scx/user_exit_info.h
- tools/testing/selftests/sched_ext/Makefile
- tools/testing/selftests/sched_ext/hotplug.bpf.c
- tools/testing/selftests/sched_ext/hotplug.c
- tools/testing/selftests/sched_ext/hotplug_test.h
- tools/testing/selftests/sched_ext/scx_test.h
- tools/testing/selftests/sched_ext/util.c
- tools/testing/selftests/sched_ext/util.h
A scheduler may implement ops.cpu_online() and ops.cpu_offline() for CPU
onlining and offlining events respectively. If a scheduler does _not_
implement these callbacks, it's indicative that they do not support
hotplug. Given that a scheduler that doesn't support hotplug is
essentially guaranteed to perform incorrectly if a hotplug event occurs,
let's update ext.c to do the sane thing, and exit the scheduler
automatically.
Given that there may be other events in the future that could cause the
scheduler to initiate an exit, we create a new enum scx_exit_code type
that reserves the top bit of the exit_code field in struct
scx_exit_info, and defines SCX_ECODE_RESTART. We could as an alternative
instead just return something like -EAGAIN to signify that user space
can try restarting the …
> scx: Exit a scheduler for unhandled hotplug events

- kernel/sched/ext.c
- tools/sched_ext/include/scx/compat.h
- tools/testing/selftests/sched_ext/hotplug.c
- tools/testing/selftests/sched_ext/util.h
We currently have a possibly tricky race w.r.t. hotplug that schedulers
don't have a good way to account for. Once a scheduler has inspected a
host topology, if a hotplug event occurs before a scheduler is attached
and loaded, then the scheduler will have no way of knowing that its view
of the host topology is incorrect. Hotplug events _after_ this are fine,
as we'll either pass the events to the scheduler, or evict the scheduler
directly. But if a hotplug event happens between inspecting the host
topology and attaching the scheduler, we have a problem.
This series addresses this by adding the capability to track a
monotonically increasing sequence number across hotplug events.
> scx: Add hotplug sequence number

- kernel/sched/core.c
- kernel/sched/cpufreq_schedutil.c
- kernel/sched/ext.c
- kernel/sched/ext.h
- kernel/sched/fair.c
- kernel/sched/sched.h
- tools/sched_ext/include/scx/common.bpf.h
- tools/sched_ext/scx_qmap.bpf.c
- tools/sched_ext/scx_qmap.c
Add `scx_bpf_cpuperf_cap()`, `scx_bpf_cpuperf_cur()` and scx_bpf_cpuperf_set()` which allows BPF schedulers to monitor and set each CPU's performance level. `ops.tick()` is added too.
> scx: Implement cpufreq support

- kernel/sched/ext.c
> scx: Mark sched_ext uclamp enabled

- kernel/sched/ext.h
The dummy scx_tick() was declared incorrectly causing build errors when !CONFIG_SCHED_CLASS_EXT. Fix it.
> scx: Fix build when !CONFIG_SCHED_CLASS_EXT

- kernel/sched/ext.c
- kernel/sched/ext.h
- tools/sched_ext/include/scx/common.bpf.h
- tools/sched_ext/include/scx/compat.h
- tools/sched_ext/scx_central.c
- tools/sched_ext/scx_flatcg.c
- tools/sched_ext/scx_qmap.bpf.c
- tools/sched_ext/scx_qmap.c
- tools/sched_ext/scx_simple.c
Reordering for consistency, indentation cleanup, minor arg renames, drop a BUILD_BUG_ON(), use SCX_OPS_OPEN consistently and so on. No functional changes intended.
> scx: Cosmetic changes from patch split

- tools/sched_ext/scx_qmap.bpf.c
With this and the latest libbpf fix which hasn't landed yet, scx_qmap can run on compat-base too.
> scx_qmap: monitor_cpuperf() also needs __COMPAT_HAS_CPUMASKS test

- kernel/sched/ext.c
- tools/sched_ext/include/scx/common.bpf.h
- tools/sched_ext/include/scx/compat.h
- tools/sched_ext/scx_qmap.bpf.c
- tools/sched_ext/scx_qmap.c
Implement ops.dump(), dump_cpu() and dump_task() which allows the BPF
scheduler to include scheduler specific information in debug dump.
The below example output from scx_qmap shows full dump of qmap's FIFO queues
and per-CPU and per-task contexts.
```
$ scx_qmap -e 3
stats  : enq=9 dsp=0 delta=9 reenq=5 deq=9 core=0 exp=0
cpuperf: cur min/avg/max=0/0/0 target min/avg/max=0/0/0
DEBUG DUMP
================================================================================
scx_qmap[1627] triggered exit kind 1025:
scx_bpf_error (test triggering error)
Backtrace:
scx_bpf_error_bstr+0x60/0x80
bpf_prog_5ab320c9dc9e846d_qmap_enqueue+0xd1/0x283
QMAP FIFO[0]:
QMAP FIFO[1]:
QMAP FIFO[2]: 1581 1583 1584 1585 1586 1588 1593 1594 1595
QMAP FIFO[3]:
QMAP FIFO[4]:
CPU states
----------
CPU 0   : nr_run=2 …
```
> Implement `ops.dump()`, `dump_cpu()` and `dump_task()`.

- .github/workflows/run-schedulers
- .github/workflows/test-kernel.yml
Enable kvm acceleration and qemu microvm to speed up CI tests inside virtme-ng.
Also adjust the regex to catch potential errors excluding a false positive triggered by the new configuration.
Link: https://github.blog/changelog/2023-02-23-hardware-accelerated-android-virtualization-on-actions-windows-and-linux-larger-hosted-runners/
Link: https://github.blog/2024-01-17-github-hosted-runners-double-the-power-for-open-source/
> ci: enable kvm support in the github workflow

- kernel/sched/ext.c
This fixes a bug introduced by 34c60754d33b ("scx: Fix scx_ops_bypass_depth going out of sync"). It added mutex_lock(scx_ops_enable_mutex) to scx_ops_bypass(), which can obviously lead to problem if scx_ops_bypass() is invoked from the disable path while someone is holding the mutex and scheduled out.
[  246.906433] INFO: task sched_ext_ops_h:1531 blocked for more than 122 seconds.
[  246.907862]       Not tainted 6.9.0-rc5-work-02067-g7f2a15fc2eb2-dirty #34
[  246.909213] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[  246.910973] task:sched_ext_ops_h state:D stack:0     pid:1531  tgid:1531  ppid:2      flags:0x00004000
[  246.913004] Sched_ext: qmap (enabled+all)
[  246.913007] Call Trace:
[  246.914486]  <TASK>
[  246.914956]  __schedule+0x750/0xcd0
[ …
> [PATCH] SCX: scx_ops_bypass() can't grab a mutex

- kernel/sched/ext.c
In sched_ext, there's currently a corner case on the hotplug path wherein a CPU may be onlined and begin scheduling _before_ we've invoked ops.cpu_online() to the scheduler. This can cause confusion by e.g. causing a scheduler to error out if it receives an ops.dispatch() call and accidentally dispatches to an invalid DSQ.
To avoid this scenario, this patch adds a per-CPU boolean variable that tracks when a CPU has been onlined from the perspective of sched_ext.
Note that this patch does not prevent _any_ callback from being invoked on that CPU. It simply prevents us from invoking ops.dispatch(), and forces us to dispatch directly to the local DSQ. We can still, however, receive e.g. ops.runnable() if a per-CPU task is dispatched to the local DSQ of the onlined CPU before the hotplug …
> scx: Dispatch locally until ops.cpu_online() invoked

- kernel/sched/ext.c
In a recent commit, we refactored bpf_exit_bstr_common() into bstr_format(). This unfortunately regressed printing output passed from BPF, as we incorrectly invoked bpf_exit_bstr_common() in the caller. Fix it.
> scx: Fix exit/error bstr formatting

- kernel/sched/ext.c
In commit 57845b39e8bb ("scx: Dispatch locally until ops.cpu_online() invoked"), we updated ext.c to only issue dispatch callbacks if we know that a CPU has been fully onlined. There were a couple of small issues with this commit, including:
1. The documentation wasn't quite right -- it said that we choose to dispatch locally, but that was a stale comment.
2. We now have two places where we're checking CPU online / offline status, which is unnecessarily confusing. scx_cpu_online matches exactly where the hotplug callbacks are invoked, so we can just use those everywhere.
Note that we can still invoke callbacks for e.g. per-CPU tasks that run on onlining CPUs before the CPU has been fully onlined. We'll update our documenation in the next patch to clarify this.
> Dispatch hotplug

- Documentation/scheduler/sched-ext.rst
- include/trace/events/sched_ext.h
- kernel/sched/ext.c
- tools/sched_ext/include/scx/common.bpf.h
- tools/sched_ext/include/scx/compat.bpf.h
- tools/sched_ext/scx_qmap.bpf.c
- Dumps can now be read through `sched_ext_dump` tracepoint.
- Dumps can now be triggered non-destructively using `sysrq-D`.
> Improve debug dump

- kernel/sched/ext.c
- kernel/sched/sched.h
- tools/sched_ext/include/scx/common.bpf.h
- rq online state could go out of sync across sched domain updates. Fixed.
- rq online is now tracked with a flag in `rq->scx.flags`.
- Dispatch buf moved into `scx_dsp_ctx`.
- Other cleanups.
> Cleanups and a small fix

- kernel/sched/ext.c
scx_ops_enable() was iterating all tasks without locking its rq and then calling get_task_struct() on them. However, this can race against task free path. The task struct itself is accessible but its refcnt may already have reached zero by the time get_task_struct() is called. This triggers the following refcnt warning.
WARNING: CPU: 11 PID: 2834521 at lib/refcount.c:25 refcount_warn_saturate+0x7d/0xe0
...
RIP: 0010:refcount_warn_saturate+0x7d/0xe0
...
Call Trace:
bpf_scx_reg+0x851/0x890
bpf_struct_ops_link_create+0xbd/0xe0
__sys_bpf+0x2862/0x2d20
__x64_sys_bpf+0x18/0x20
do_syscall_64+0x3d/0x90
entry_SYSCALL_64_after_hwframe+0x46/0xb0
This can also affect other loops as it can call sched functions on tasks which are already destroyed. Let's fix it by making scx_task_iter_filtered_locked() …
> scx: Close a small race window in the enable path which can lead to use-after-free

- tools/sched_ext/include/scx/compat.h
- tools/sched_ext/scx_central.c
- tools/sched_ext/scx_flatcg.c
- tools/sched_ext/scx_qmap.c
- tools/sched_ext/scx_simple.c
Receive the skel.attach() fix.
> scx: Sync from the SCX repo

- Documentation/scheduler/sched-ext.rst
Fix "implemenation" to "implementation".
> scx: Fix typos

- tools/testing/selftests/sched_ext/Makefile
- tools/testing/selftests/sched_ext/create_dsq.bpf.c
- tools/testing/selftests/sched_ext/create_dsq.c
DSQs have their own lifecycle which is protected by RCU. Let's add a simple selftest that just stresses the create / free path so we get a bit of coverage.
> scx: Add a selftest for creating and destroying a DSQ

- kernel/sched/ext.c
Origin implementation of function `highest_bit` utilize the function of `fls()` to calculate the most significant bit of the input parameter `flags`. Normally we can return the mask with `1 << (fls(flags) - 1)`, but `fls(flags)` will return 0 if the value of `flags` is 0, which will cause the evaluation become `1 << (-1)` and it's illegal. So we use a branch to determine whether the return value of `fls(flags)` is 0.
We can remove the use of branch first left shift `fls(flags)` number of bits and then right shift 1 bit. When the value of `fls(flags)` is 0 then this evaluation will simply become 0 without any error. As more values other than 0, evaluation is the same as it did for `1 << (fls(flags) - 1)`.
This implementation can prevent any possible branch prediction fault and pure shift …
> scx: Branchless implementation of highest_bit

- tools/sched_ext/include/scx/common.bpf.h
- tools/sched_ext/scx_central.bpf.c
- tools/sched_ext/scx_flatcg.bpf.c
- tools/sched_ext/scx_simple.bpf.c
> Sync with scx repo

- kernel/sched/ext.c
We weren't synchronizing the boot CPU's online state with scx_rq's online state. This however was getting hidden through the RQ_ONOFF_TOPOLOGY update calls. 3a4476944ee2 ("scx: Replace scx_cpu_online percpu var with SCX_RQ_ONLINE flag") masked RQ_ONOFF_TOPOLOGY calls leaving the boot CPU marked offline from SCX's POV always forcing the CPU into local bypass mode, likely leading to reported interactivity problems on scx_rusty.
Fix it by synchronizing SCX_RQ_ONLINE with CPU's online states in init_sched_ext_class().
> SCX: Synchronize boot CPU's online state with SCX_RQ_ONLINE

- kernel/sched/ext.c
- tools/testing/selftests/sched_ext/Makefile
- tools/testing/selftests/sched_ext/dsp_local_on.bpf.c
- tools/testing/selftests/sched_ext/dsp_local_on.c
@Gabant noticed in https://github.com/sched-ext/sched_ext/issues/218 that our
comparison is backwards in dispatch_to_local_dsq() when determining if the
destination rq in a local dispatch is idle. This could cause us to fail to send
resched IPIs to those remote DSQs when a scheduler uses SCX_DSQ_LOCAL_ON when
dispatching. Thankfully, the issue doesn't happen if dispatching to a local DSQ
from the ops.select_cpu() path, as a resched IPI is sent by the core scheduler
if a task is migrated to an idle core on the wakeup path.
Let's fix it.
Reported-by: @Gabant
Signed-off-by: David Vernet <void@manifault.com>
> scx: Fix local DSQ comparison in dispatch_to_local_dsq()

- kernel/sched/core.c
Tejun pointed out that if we set or unset the hotplug online flag before we invoke the relevant hotplug callbacks, schedulers could get confused because they could begin receiving callbacks on a CPU before (or after) they're notified that a CPU is online (or offline).
Let's reverse the order to fix that.
> scx: Flip order of scx_rq_{de}activate()

- kernel/sched/ext.c
- kernel/sched/ext.h
- Whitespace and comment adj.
- Use sched_class_above() instead of naked comparison.
- Reorder hotplug functions.
- s/promote_op_nth_arg()/set_arg_maybe_null()/. Relocate @arg_n after @op and remove promote_op_arg().
- Reorder declarations and dummy defs in kernel/sched/ext.h.
No functional changes.
> scx: Cosmetic changes

- kernel/sched/ext.c
Quick fix of spelling in dispatch_to_local_dsq_lock comment.
> scx: Fix spelling in function comment

- kernel/sched/ext.c
__scx_bpf_consume_task() should test whether the task is still on the DSQ that's being iterated before erroring out if it's on a local DSQ. Otherwise, another racing consumer can move the task to a local DSQ triggering a spurious error. Relocate the error condition.
> scx: Fix error condition check in __scx_bpf_consume_task()

- tools/testing/selftests/sched_ext/init_enable_count.c
__COMPAT_SCX_OPS_SWITCH_PARTIAL is no more. Use SCX_OPS_SWITCH_PARTIAL instead.
> selftests/sched_ext: Build fix
